const labels_CN = {
  personalInfo: {
    sectionName: '个人信息',
    firstName: '名字',
    surname: '姓氏',
    userTel: '电话号码',
    userEmail: '邮箱',
    linkedIn: '领英',
  },
  educationInfo: {
    sectionName: '教育信息',
    currentUni: '大学',
    City: '城市',
    State: '州',
    currentCountry: '国家',
    currentDegree: '主修学位',
    currentMajor: '专业',
    GraduationDate: '毕业日期',
    Score: 'GPA和荣誉',
    Achievement: '成就',
    currentCourses: '课程',
  },
  workExperience: {
    sectionName: '工作经历',
    internRole: '职位头衔',
    GroupName: '组名',
    internCompany: '公司',
    City: '城市',
    State: '州',
    Country: '国家',
    StartDate: '开始日期',
    EndDate: '结束日期',
    WorkSummary: '工作摘要',
    WorkDetail: '工作细节',
  },
  projectExperience: {
    sectionName: '项目经验',
    getProject: '项目标题',
    CourseName: '课程名称',
    SchoolName: '学校',
    City: '城市',
    State: '州',
    Country: '国家',
    StartDate: '开始日期',
    EndDate: '结束日期',
    ProjectSummary: '项目摘要',
    ProjectDetail: '项目细节',
  },
  researchExperience: {
    sectionName: '研究经验',
    ResearchTitle: '研究标题',
    SchoolName: '学校',
    City: '城市',
    State: '州',
    Country: '国家',
    StartDate: '开始日期',
    EndDate: '结束日期',
    ResearchSummary: '研究摘要',
    ResearchDetail: '研究细节',
  },
  publicationsPresentations: {
    sectionName: '出版物和演示',
    getConference: '出版物和演示',
  },
  skillsActivitiesInterests: {
    sectionName: '技能、活动和兴趣',
    language1: '语言1',
    language2: '语言2',
    getSkills: '技能',
    IndustrySkills: '行业技能',
    RelevantCertificates: '证书',
    VolunteerWork: '志愿者工作',
    interst1: '兴趣',
  },
};

export default labels_CN;
