const labels_EN = {
  personalInfo: {
    sectionName: 'Personal',
    firstName: 'First Name',
    surname: 'Last Name',
    userTel: 'Phone Number',
    userEmail: 'Email',
    linkedIn: 'LinkedIn',
  },
  educationInfo: {
    sectionName: 'Education',
    currentUni: 'University',
    City: 'City',
    State: 'State',
    currentCountry: 'Country',
    currentDegree: 'Degree in Major',
    currentMajor: 'Major',
    GraduationDate: 'Graduation Date',
    Score: 'GPA and Honors',
    Achievement: 'Achievement',
    currentCourses: 'Courses',
  },
  workExperience: {
    sectionName: 'Work Experience',
    internRole: 'Position Title',
    GroupName: 'Group Name',
    internCompany: 'Company',
    City: 'City',
    State: 'State',
    Country: 'Country',
    StartDate: 'Start Date',
    EndDate: 'End Date',
    WorkSummary: 'Work Summary',
    WorkDetail: 'Work Details',
  },
  projectExperience: {
    sectionName: 'Project Experience',
    getProject: 'Project Title',
    CourseName: 'Course Name',
    SchoolName: 'School',
    City: 'City',
    State: 'State',
    Country: 'Country',
    StartDate: 'Start Date',
    EndDate: 'End Date',
    ProjectSummary: 'Project Summary',
    ProjectDetail: 'Project Details',
  },
  researchExperience: {
    sectionName: 'Research Experience',
    ResearchTitle: 'Research Title',
    SchoolName: 'School',
    City: 'City',
    State: 'State',
    Country: 'Country',
    StartDate: 'Start Date',
    EndDate: 'End Date',
    ResearchSummary: 'Research Summary',
    ResearchDetail: 'Research Details',
  },
  publicationsPresentations: {
    sectionName: 'Publications and Presentations',
    getConference: 'Publications and Presentations',
  },
  skillsActivitiesInterests: {
    sectionName: 'Skills, Activities, and Interests',
    language1: 'Language 1',
    language2: 'Language 2',
    getSkills: 'Skills',
    IndustrySkills: 'Industry Skills',
    RelevantCertificates: 'Certificates',
    VolunteerWork: 'Volunteer Work',
    interst1: 'Interests',
  },
};

export default labels_EN;
